services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user-database'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'

