services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_DB=user-database'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5438:5432'

