spring:
  application:
    name: musalog-user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-database
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}::${spring.application.instance_id:${random.value}}
        register: true
        enabled: true
        deregister: on
      enabled: true

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 120
  issuer: terenin

